# Generated by Django 3.2.16 on 2023-04-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='label1',
            field=models.CharField(default='azerty', max_length=255),
            preserve_default=False,
        ),
    ]
