# Generated by Django 3.2.16 on 2023-04-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_label1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='label1',
        ),
    ]
